### ISSUE TITLE
Static analysis and type-checking of df column names

### ISSUE THREAD

**Issue by alexlatif** [static-frame/static-frame#795]
Hi Chris starting a thread on the way one could achieve type-hint style syntax and a static-analysis checks on column names for data frames. This is something that seems hard for Pandas to support, defining custom Pandera's schema's are hard to configure typing for and there are so many restrictions on their schema validators that can quite easily be achieved with custom defined validation where needed.

Imagine one is in a part of the system whose data comes in at runtime, the system knows a data frame is available and all python objects are subsequently type hinted, but the column names of the data frame.

How would you approach this? It seems like a defining a meta structure is required, but I am trying to think through a simple way of going about this. This also seems perfect for static-frame to support given the values of immutability.

**Comment by olivercoleman-switchdin** [comment]
This is something I'd love to have, too - i.e. static analysis for type checking. I posted this more limited issue just now for type hints for Series https://github.com/static-frame/static-frame/issues/818, but type hints for Frames would be the holy grail.

Pandera doesn't seem like a viable option:
* it seems to be based primarily on Pandas so there'll be API mismatches?;
* "Mypy static type-linting is supported for only pandas dataframes";
* "This functionality is experimental 🧪. Since the [pandas-stubs](https://github.com/pandas-dev/pandas-stubs) type stub annotations don’t always match the official [pandas effort to support type annotations](https://github.com/pandas-dev/pandas/issues/28142#issuecomment-991967009)), installing the pandera[mypy] extra may yield false positives in your pandas code" 

See https://pandera.readthedocs.io/en/stable/mypy_integration.html#mypy-integration

**Comment by alexlatif** [comment]
@olivercoleman-switchdin not relevant to solving the need for data frames and the problem you are solving for. But have come to realize that in the end unless you are doing things in aggregation, from a data pipeline perspective I have honed in on just using series where you have full control over this. I guess a simple interface to and from df to s is perhaps the best patch on this. I just dont ever see static typing as a pandas philosophy nor something that would be practically feasible

**Comment by olivercoleman-switchdin** [comment]
FYI https://spark.apache.org/docs/latest/api/python/user_guide/pandas_on_spark/typehints.html

**Comment by flexatone** [comment]
StaticFrame 2.0 defines `Frame`, `Series`, and many other containers as generic. `Frame` are defined as generic to their index, columns, and columns types (using the new variadic generic, `TypeVarTuple`).

For example, a `Frame` with string index, integer columns, and three columns of ints, strings, and Booleans will be define as follows:

```python
f1: sf.Frame[sf.Index[np.str_], sf.Index[np.int64], np.int64, np.str_, np.bool_]
```
These are pyright checkable (mypy soon we hope). If you want run time checks, you can use the new `Frame.via_type_clinic` interfaces, as well as a new `sf.CallGuard.call` decorator that uses hints for run-time checks.

Finally, Pandera-style runtime validations can be added to type hints using `tp.Annotated` generics. StaticFrame 2.0 incldues a number of practical validators, as well as support for arbitrary functions called per column and row.

More on this in an upcoming article. I hope to release StaticFrame 2.0 in a few weeks.

**Comment by flexatone** [comment]
Thanks, @strazto , for the feedback. While staying within the built-in capacities of Python type annotations, directly associating columnar types by column label rather than position is not really possible. While ordered sequences of types certainly does get challenging to maintain at large scales, obligating users to create separate schema classes incurs other tradeoffs.

One mitigation is that, using the `TypeVarTuple` `Unpack` syntax, we can flexibly type regions of many (tens, hundreds) uniformly typed columns, something that would be impractical if types had to be associated with labels. Here is brief overview of what that looks like:

https://static-frame.readthedocs.io/en/latest/articles/ftyping.html#the-expressive-power-of-typevartuple
