### ISSUE TITLE
Allow `sf.Yarn` to support buses with non-unique names, if the inner frame names are unique!

### ISSUE THREAD

**Issue by chaburkland** [static-frame/static-frame#917]
**Description**

Right now, it is not possible to construct a `Yarn` object from buses that don't have unique names. I don't necessarily think this is mandatory, as long as the inner frame names are unique.

Note: this is strongly linked to another Yarn feature request: https://github.com/static-frame/static-frame/issues/916

**Example**

```python
import frame_fixtures as ff
import static_frame as sf

ff.parse("s(3,3)")
b1 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f1"),))
b2 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f2"),))
b3 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f3"),))

sf.Yarn.from_buses((b1, b2, b3), retain_labels=True)  # This fails, but I think it shouldn't! Expectation below
"""
<Yarn>
<IndexHierarchy>
None             f1    Frame
None             f2    Frame
None             f3    Frame
<object>         <<U2> <object>
"""
```

**Platform**

Run the following function (static-frame >= 0.8.1) and provide the results to define your platform and environment:

```python
<Series: platform>
<Index>
platform           Linux-5.4.0-174-generic-x86_64-with-glibc2.31
sys.version        3.11.4 (main, Feb  7 2024, 10:52:06) [GCC 9.4.0]
static-frame       2.2.3
numpy              1.24.3
pandas             1.5.3
xlsxwriter         3.1.0
openpyxl           3.0.9
xarray             <ModuleNotFoundError>
tables             3.8.0
pyarrow            12.0.1
msgpack            (1, 0, 0)
msgpack_numpy      None
<<U13>             <object>
```

**Comment by flexatone** [comment]
Thanks for this interesting suggestion.

To restate, your point is that, in your example, a `Yarn` should be created from these `Bus` when `retain_labels` is `True`  because the implied resulting `IndexHierarchy` will be unique. In this case, the label of each `Bus` (its `name`) is None, so an `IndexHierarchy` with an outer label of `None` would be appropriate.

The same shortcoming can be seen here:

```python
>>> b1 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f1"),)).rename('b')
>>> b2 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f2"),)).rename('b')
>>> b3 = sf.Bus.from_frames((ff.parse("s(3,3)").rename("f3"),)).rename('b')
>>> sf.Yarn.from_buses((b1, b2, b3), retain_labels=True) 
Traceback (most recent call last):
static_frame.core.exception.ErrorInitIndexNonUnique: Labels have 2 non-unique values, including 'b'.
```
The resulting `IndexHierarchy` must be unique, but there is no requirement that what becomes the outer labels is unique, especially when the user has already opted in to `retain_labels`. I expect this is result of the order in which indices are built. 

I fully support this change and will explore an implementation.
