### ISSUE TITLE
Grouping and aggregating should be easy (possibly even for idiots like me)

### ISSUE THREAD

**Issue by olivercoleman-switchdin** [static-frame/static-frame#942]
**Description**

I want to like SF, I really do, it's conceptually awesome. But I'm finding it almost impossible to actually use.

I'm not sure if this is because: a) I'm an idiot; b) lack of documentation; or c) a user-unfriendly API.

It's true, every class, attribute, and method does seem to have some kind of documentation, but:
* arguments to functions are often undocumented and not always obvious from their names.
* the examples given typically only show basic usage (in the API docs, quickstart guide, notebook examples).

Perhaps if there was a community slack channel to ask for help?

I'm assuming I can't be the only (idiot) who is ready to give up and go back to flawed but easy-to-use Pandas...

**Example**

I've spent around 4 hours trying to implement the below very simple Pandas code using SF. My main angle of attack was trying to use `Frame.iter_group*`. I got as far as getting it to show me frames for each grouping on column `a` but could not figure out how to make it aggregate with different functions for each column.

```python
df = pd.DataFrame({
    "a": [1, 2, 2, 3],
    "b": [4, 2, 3, 6],
    "c": [1, 2, 3, 3]
})
df = df.groupby(["a"]).agg({"b": "sum", "c": "min"})
#    b  c
# a      
# 1  4  1
# 2  5  2
# 3  6  3
```

**Comment by flexatone** [comment]
Many thanks for your feedback, and apologies for the frustration.

Your points about shortcomings in the documentation are well taken. A community Slack is a fine idea, and I welcome any question as issues here too.

The particular case you show is admittedly not as concise to do in SF. Part of the reason is that we wanted to reject the heterogeneous behavior and output types returned by Pandas `gruopby` and insist on only returning `Series`. For anything more complex, we are generally implementing a processor of iterated groups and then building up a new `Frame`.  In this case it ends up quite verbose, but is (painfully?) explicit.

I agree that this case begs for a less complex interface; I am certainly open to ideas and already have some in mind. 

So we can take your `DataFrame` and convert it to a `Frame`:

```python
>>> df = pd.DataFrame({
...     "a": [1, 2, 2, 3],
...     "b": [4, 2, 3, 6],
...     "c": [1, 2, 3, 3]
... })
>>> df
   a  b  c
0  1  4  1
1  2  2  2
2  2  3  3
3  3  6  3
>>> f = sf.Frame.from_pandas(df)
>>> f
<Frame>
<Index> a       b       c       <object>
<Index>
0       1       4       1
1       2       2       2
2       2       3       3
3       3       6       3
<int64> <int64> <int64> <int64>
```

Using the `iter_group().apply()` idiom, we are going to return a `Series` by applying a function to each group given as a `Frame`. We could capture these two values per group as a `tuple`, which is not what you want, but illustrates the basic functionality.

```python
>>> f.iter_group('a').apply(lambda f: (f['b'].sum(), f['c'].min()))
<Series>
<Index: a>
1          (4, 1)
2          (5, 2)
3          (6, 3)
<int64>    <object>
```

We have a number of other approaches. You can see with `iter_group_items()` we can iterate over pairs of index label, group `Frame`.

```python
>>> f.iter_group_items('a').apply(lambda i, f: (i, (f['b'].sum(), f['c'].min())))
<Series>
<Index: a>
1          (1, (4, 1))
2          (2, (5, 2))
3          (3, (6, 3))
<int64>    <object>
```

We can  combine that with an `apply_iter()` which does not eagerly apply, but applies and yields, providing an iterator we can feed into `Frame.form_records_items()`:

```python
>>> sf.Frame.from_records_items(f.iter_group_items('a').apply_iter(lambda i, f: (i, [f['b'].sum(), f['c'].min()])))
<Frame>
<Index> 0       1       <int64>
<Index>
1       4       1
2       5       2
3       6       3
<int64> <int64> <int64>
```

So that gets us most of the way, but we still have to have add the column names.

So yes, I agree, this particular type of group aggregation is not easy and can be improved! In our usage, however, when we need to do complex things with groups, we are more often writing a function and then building up components of a final `Frame`:

```python
def process(f: Frame) -> Iterator[sf.Series]:
    for i, f_group in f.iter_group_items('a'):
        # do complex work with f_group
        yield sf.Series((f_group['b'].sum(), f_group['c'].min()), name=i, index=f_group.columns.drop.loc['a'])

f2 = sf.Frame.from_concat(process())
```

But again, I agree that your example begs for an explicit, specialized interface.

Again, thanks for the feedback, I welcome information about any other pain points you have encountered.

**Comment by olivercoleman-switchdin** [comment]
Thanks so much for the detailed explanation. I got it working :)
However, maybe I'm doing something wrong, but it's taking around *60 times longer* to do the equivalent operation in SF vs Pandas.

Pandas takes 0.07 seconds for this:
```python
pdf = frame.frame.to_pandas()
pdf = pdf.groupby("time").agg({"count": "sum", "max": "max", "min": "min", "sum": "sum"})
```
Whereas SF takes around 4.3 seconds for the equivalent:
```python
    frame = sf.Frame.from_records_items(
        frame.frame.iter_group_items("time").apply_iter(
            lambda row_idx, group: (
                row_idx,
                [group["count"].sum(), group["max"].max(), group["min"].min(), group["sum"].sum()],
            )
        ),
        columns=["count", "max", "min", "sum"],
        index_constructor=sf.IndexSecond,
    )
```
The only difference I can see is the `index_constructor=sf.IndexSecond`, but I'm guessing this isn't a major component of the time.
 
The frame has just the five columns, and ~1440 rows.

**Comment by olivercoleman-switchdin** [comment]
Thank you so much for the detailed explanation. I got it working :)
However, maybe I'm doing something wrong, but SF is taking around *50 times* longer than Pandas to do the equivalent operation. Let me know if I should post this as a new issue if that's preferable.

Pandas is taking ~0.11 seconds for this:
```python
pdf = pdf.groupby("time").agg({"count": "sum", "max": "max", "min": "min", "sum": "sum"})
pdf.set_index(pd.DatetimeIndex(pdf.index.astype("datetime64[s]"), tz="UTC"), inplace=True)
```

Whereas SF is taking ~5.5 seconds for this:
```python
     merged_timestamps_frame = sf.Frame.from_records_items(
        frame.iter_group_items("time").apply_iter(
            lambda row_idx, group: (
                row_idx,
                [group["count"].sum(), group["max"].max(), group["min"].min(), group["sum"].sum()],
            )
        ),
        columns=["count", "max", "min", "sum"],
        index_constructor=sf.IndexSecond,
    )
```

Also, while we're here, reindexing/relabelling is taking around 18 times longer.

Pandas takes ~0.07 seconds for this:
```python
    pdf = pdf.reindex(
        index=pd.date_range(
            start=period_start_inclusive,
            end=period_end_exclusive - interval,
            freq=pd.Timedelta(interval.in_seconds(), "s"),
        ),
    )
    pdf.fillna({"count": 0}, inplace=True)
    pdf["count"] = pdf["count"].astype(int)
```

SF takes ~1.25 seconds for this:
```python
   constant_interval_frame = merged_timestamps_frame.reindex(
        index=sf.IndexSecond(
            pendulum.interval(period_start_inclusive, period_end_exclusive - interval).range(
                "seconds", interval.in_seconds()
            ),
            name="time",
        ),
        fill_value={"count": 0, "max": np.nan, "min": np.nan, "sum": np.nan},
    )
```

**Comment by flexatone** [comment]
I am away from my machine for a few days and unable to explore this myself, but one way to immediately improve performance with row-wise constructors like this is to supply a `dtypes` argument to `from_records_items`. The generality of this interface means that columnar types have
to be discovered if not provided, and that is slow. Providing a `dict` mapping column name to type for the `dtypes` argument allows that evaluation to be skipped, improving performance.

**Comment by olivercoleman-switchdin** [comment]
Thanks for the tip! Perhaps I'm doing it wrong but I couldn't make it faster with this. I've attached an example notebook for testing.
[pd_sf_group_agg_test.zip](https://github.com/user-attachments/files/15878471/pd_sf_group_agg_test.zip)

**Comment by flexatone** [comment]
Many thanks, @olivercoleman-switchdin , for the performance test. I was able to integrate it into SF's performance profiling library (https://github.com/static-frame/static-frame/pull/946)

The initial implementation, following my suggestions of using `from_records_items`, `iter_group_items`, and `apply_iter` indeed performed poorly, 100x slower than Pandas with a 3k-row `Frame` (SF is Native, Pandas is Reference):

```
name                            iterations Native Reference n/r     r/n    win   status explanation
FrameIterGroupAggregate.numeric 100        4.3135 0.0418    103.301 0.0097 False ? 
```

This particular scenario, with numerous very small groups (each of only two rows) is a particular detriment for this approach.

Exploring an alternative, I made use of ``iter_group_array_items`` instead of ``iter_group_items``, which requires a processing function that deals only with arrays and removes some intermediate objects. This improved under-performance to 27x slower than Pandas:

```
name                            iterations Native Reference n/r     r/n    win   status explanation
FrameIterGroupAggregate.numeric 100        1.1413 0.0414    27.5822 0.0363 False ? 
```
Better, but still not good.

To prove the point about the small size of the groups, if I increase the group size from 2 to 300, SF and Pandas are tied:

```
name                            iterations Native Reference n/r    r/n    win  status explanation
FrameIterGroupAggregate.numeric 100        0.0378 0.0379    0.9979 1.0021 True ?      
```

So a key issue is that small group sizes incur significant overhead in aggregate `Frame` formation.

Next, I will explore a specialized solution for this style of `Frame` creation: the very general approach used here misses the opportunity for pre-allocating (and then filling) final columnar arrays, which is likely to significantly improve performance.

**Comment by flexatone** [comment]
Hi @olivercoleman-switchdin :

In terms of performance, as shown above, SF still underperforms Pandas for very small groups, but approaches and may out-perform Pandas with larger groups.

In terms of interface, SF now has a `reduce` interface that supports maybe all of the functionality made available by the Pandas `agg` interface. The SF interface makes inputs and outputs explicit by using chained methods, and the user provides real functions, not strings:

```python
>>> df = pd.DataFrame({
...     "a": [1, 2, 2, 3],
...     "b": [4, 2, 3, 6],
...     "c": [1, 2, 3, 3]
... })
>>> 
>>> f = sf.Frame.from_pandas(df)
>>> f.iter_group('a').reduce.from_label_map({'b':np.sum, 'c':np.min}).to_frame()
<Frame>
<Index> b       c       <object>
<Index>
1       4       1
2       5       2
3       6       3
<int64> <int64> <int64>
```
More examples of the `reduce` interface can be seen here:

https://github.com/static-frame/static-frame/pull/946#issuecomment-2251677945

These features will be part of the 2.11 release.
